FROM node:10-jessie

WORKDIR /usr/app

RUN npm i -g react-scripts
RUN npm i -g serve

COPY package.json /usr/app

RUN npm i

COPY . /usr/app 

ENV REACT_APP_SITE_TITLE="Declan Woods"

RUN npm run build-declan 
ADD public/.well-known /usr/app/build
ADD serve.json /usr/app/build/serve.json

EXPOSE 80

CMD ["serve", "build", "-l", "80"]
