FROM node:10-jessie

WORKDIR /usr/app

RUN npm i -g react-scripts
RUN npm i -g serve

COPY package.json /usr/app

RUN npm i

COPY . /usr/app 

ENV REACT_APP_SITE_TITLE="Hayden Woods"

RUN npm run build-hayden 

EXPOSE 80

CMD ["serve", "-s", "build", "-l", "80"]